server:
  port: 8091  # Define the application port

spring:
  application:
    name: AudioProcessingApplication

  datasource:
    url: jdbc:mysql://localhost:3306/audio_db # In-memory database for development
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "[password]"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO  # Set logging level
    turing.example.audioprocessing: DEBUG  # Debug logging for your application package
